### ISSUE TITLE
Add selectors filter for the searches index list

### ISSUE THREAD

**Issue by eduayme** [eduayme/Rescue-app#25]
Adding some selectors at the bottom of the page to filter all searches by:

- [x] Status
- [x] Date range
- [x] Village
- [x] Region

**Comment by Jayashrri** [comment]
Hey, I would like to work on this. May I know which fields in the Searches table in the DB corresponds to each of these filter fields? Thank you.

**Comment by eduayme** [comment]
Yes, for sure. You can find the database structure in database->migrations. Filter selectors in the list view should allow filtering:

- Status = searches.status
- Date range = searches.date_start && searches.date_finalization (date range selector)
- Village = searches.municipality_last_place_seen
- Region = searches.region
