### ISSUE TITLE
Footer should be stick at bottom

### ISSUE THREAD

**Issue by azhsetiawan** [eduayme/Rescue-app#40]
Hi @eduayme

Maybe layout can be imporoved, especially footer.
That's better if footer stick/fixed at bottom screen

![rescue-Screen Shot 2019-10-15 at 15 48 10](https://user-images.githubusercontent.com/3045602/66817480-f7d24a00-ef65-11e9-9223-ff31059d7b60.png)

**Comment by eduayme** [comment]
Hi @azhsetiawan 

Yes, good idea! Thanks

**Comment by eduayme** [comment]
@azhsetiawan I have tried to do it. The problem is when scrolling, in pages with a height bigger than the screen, the footer scrolls too (it should be fixed at the bottom of the entire page) so this is why is not sticked.

**Comment by azhsetiawan** [comment]
@eduayme let me try to make it
